# -*- coding: utf-8 -*-
"""no1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uG4vblT3fm4XlMm3nRkHVelTqLSXZkUa
"""

#Nadia Alifiani Raissa Pansera
#No1a

import numpy as np
inputs = [1.0, 2.0, 2.1, 2.2, 3.1, 3.2, 4.1, 4.2, 5.1, 5.2]
weights = [3.0, 2.7, 2.3, 3.3, 5.2, 1.1, 2.9, 2.8, 6.2, 3.4]
bias = 2.1

output = np.dot(weights, inputs) + bias
print(output)